# NOTES
# - This docker-compose.yml file is used to run 6 instances of ayamgoreng with 6 different roles
# - 6 instances for each role (scale: 6)

version: '3'

services:
  mage:
    image: joki-ml-bang
    command: ["./ayamgoreng", "MAGE"]
    scale: 6

  fighter:
    image: joki-ml-bang
    command: ["./ayamgoreng", "FIGHTER"]
    scale: 6

  mm:
    image: joki-ml-bang
    command: ["./ayamgoreng", "MM"]
    scale: 6

  assassin:
    image: joki-ml-bang
    command: ["./ayamgoreng", "ASSASSIN"]
    scale: 6

  support:
    image: joki-ml-bang
    command: ["./ayamgoreng", "SUPPORT"]
    scale: 6
  
  tank:
    image: joki-ml-bang
    command: ["./ayamgoreng", "TANK"]
    scale: 6